version: "3.9"

services:
  keycloak-db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=keycloak

  keycloak:
    build: keycloak
    ports:
      - "8080:8080"
      - "8443:8443"
    environment:
      - KC_DB=postgres
      - KC_DB_USERNAME=root
      - KC_DB_PASSWORD=root
      - KC_DB_URL=jdbc:postgresql://keycloak-db/keycloak
      - KC_HOSTNAME=localhost
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: start --optimized
    depends_on:
      - keycloak-db

  frontend:
    build: 
      context: frontend/simple-auth
      dockerfile: ../Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXTAUTH_SECRET=eo7z7W5framDrmBnagBhhB2u0rNdKsMCAWNDW4s+z1o+1Hs3kKHsmVVnH0LjfxzUoukdnp/ySZrE/i+lEFgObA==
      - NEXTAUTH_URL=http://localhost:3000
      - KEYCLOAK_ID=frontend
      - KEYCLOAK_SECRET=DhWehPMwcs53HIGLj9LU36JIBxTfLYoq
      - KEYCLOAK_ISSUER=https://keycloak:8443/realms/sample-app
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    depends_on:
      - keycloak

  # backend:
  #  build:
  #    context: backend
  #  depends_on:
  #    - keycloak
